
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            America/Sao_Paulo # eg. Asia/Kathmandu
locale:              pt_br # eg. en_us
name:				         site name
title:               TheTimeTunnel
tagline:             'tagline'
description:         'TheTimeTunnel | Development Team'
url:                 https://thetimetunnel.github.io/
rss:                 feed.xml
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                '/assets/imagesg/icon.png' # /assets/img/icon.png [best 300px X 300px]
disqus:              thetimetunnel # get it on https://disqus.com/admin/

author:
  name:           	 William Tumeo
  url:            	 https://thetimetunnel.github.io/
  facebook:          williamd1k0
  twitter:           williamd1k0
  google_plus:       +williamtumeo
  #linkedin:          username
  #dribbble:          username
  pinterest:         username
  #kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
